force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description for the Book</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BookManagementController.cls
public with sharing class BookManagementController {
    public class BookWrapper {
        public BookWrapper() {}

        @AuraEnabled
        public String name;
        @AuraEnabled
        public String recordId;
        @AuraEnabled
        public String authorId;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public String authorName;


    }

    @AuraEnabled(cacheable=true)
    public static List<BookWrapper> getAllBooks() {
        List<Book__c> books = [
            SELECT Id, Name, Author__c, Author__r.Name, Description__c, CreatedDate
            FROM Book__c WHERE Author__c != null ORDER BY Name LIMIT 50
        ];
        List<BookWrapper> wrappers = new List<BookWrapper>();
        for (Book__c book : books) {
            BookWrapper wrapper = new BookWrapper();
            wrapper.recordId = book.Id;
            wrapper.name = book.Name;
            wrapper.description = book.Description__c;
            wrapper.authorId = book.Author__c;
            wrapper.authorName = book.Author__r.Name;

            wrappers.add(wrapper);
        }
        return wrappers;
    }

    @AuraEnabled(cacheable=true)
    public static List<Author__c> getAllAuthors() {
        return [SELECT Id, Name FROM Author__c ORDER BY Name LIMIT 50];
    }

    @AuraEnabled
    public static Book__c upsertBook(Id bookId, String name, String description, Id authorId) {
        Book__c book = new Book__c(
            Id = bookId,
            Name = name,
            Description__c = description,
            Author__c = authorId
        );

        upsert book;
        return book;
    }

    @AuraEnabled
    public static void deleteBook(Id bookId) {
        Database.delete(bookId);
    }

    @AuraEnabled
    public static void insertAuthor(String name) {
        insert new Author__c(
            Name = name
        );
    }

    @AuraEnabled
    public static void deleteAuthorAndRelatedBooks(Id authorId) {
        Database.delete(authorId);
    }
}